/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Quinze;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Main classUnderTest = newMain();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
